version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis_service
    ports:
      - "6379:6379"
  
  web:
    build: ./web
    container_name: node_web_service
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
